// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrUxjqHvwaMLlSBTTQ8dDV6QXP9geGMmU',
    appId: '1:1045532070797:web:74889d2c3300eed9a423c4',
    messagingSenderId: '1045532070797',
    projectId: 'holyparish',
    authDomain: 'holyparish.firebaseapp.com',
    storageBucket: 'holyparish.firebasestorage.app',
    measurementId: 'G-KLX8W8RXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0EpETSdgGhTh1Bqz1wUin1VlTxFaDKQ',
    appId: '1:1045532070797:android:c08265ff3d27e5e3a423c4',
    messagingSenderId: '1045532070797',
    projectId: 'holyparish',
    storageBucket: 'holyparish.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXQpz4KUWBdVpIspakwymFvMut6SqIsk',
    appId: '1:1045532070797:ios:65f867625963a6e1a423c4',
    messagingSenderId: '1045532070797',
    projectId: 'holyparish',
    storageBucket: 'holyparish.firebasestorage.app',
    iosBundleId: 'com.example.parishrecord',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXQpz4KUWBdVpIspakwymFvMut6SqIsk',
    appId: '1:1045532070797:ios:65f867625963a6e1a423c4',
    messagingSenderId: '1045532070797',
    projectId: 'holyparish',
    storageBucket: 'holyparish.firebasestorage.app',
    iosBundleId: 'com.example.parishrecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrUxjqHvwaMLlSBTTQ8dDV6QXP9geGMmU',
    appId: '1:1045532070797:web:c4af44a59a036709a423c4',
    messagingSenderId: '1045532070797',
    projectId: 'holyparish',
    authDomain: 'holyparish.firebaseapp.com',
    storageBucket: 'holyparish.firebasestorage.app',
    measurementId: 'G-TCNXQQXBQN',
  );
}
