// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4IVkXqxZtSjuv_XG2-VktbHwKRPaBmk',
    appId: '1:92541925437:web:4bd0f0414fb9306a519254',
    messagingSenderId: '92541925437',
    projectId: 'holyparish-af472',
    authDomain: 'holyparish-af472.firebaseapp.com',
    storageBucket: 'holyparish-af472.firebasestorage.app',
    measurementId: 'G-THHPFR7S75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUbGlRr-53H5UjNpiaVBBk_XesfFZcug',
    appId: '1:92541925437:android:9a1cd349585bf8c1519254',
    messagingSenderId: '92541925437',
    projectId: 'holyparish-af472',
    storageBucket: 'holyparish-af472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKStQ2lJoHUkBGexD9BkkitUoCtNxyoh0',
    appId: '1:92541925437:ios:6b1df0f8c0163a1f519254',
    messagingSenderId: '92541925437',
    projectId: 'holyparish-af472',
    storageBucket: 'holyparish-af472.firebasestorage.app',
    iosBundleId: 'com.example.parishrecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKStQ2lJoHUkBGexD9BkkitUoCtNxyoh0',
    appId: '1:92541925437:ios:6b1df0f8c0163a1f519254',
    messagingSenderId: '92541925437',
    projectId: 'holyparish-af472',
    storageBucket: 'holyparish-af472.firebasestorage.app',
    iosBundleId: 'com.example.parishrecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4IVkXqxZtSjuv_XG2-VktbHwKRPaBmk',
    appId: '1:92541925437:web:0442e277efe3a190519254',
    messagingSenderId: '92541925437',
    projectId: 'holyparish-af472',
    authDomain: 'holyparish-af472.firebaseapp.com',
    storageBucket: 'holyparish-af472.firebasestorage.app',
    measurementId: 'G-CRES5L6M2K',
  );
}
